name: ci-fullstack-workflow
# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  workflow_dispatch:
  push:
    branches: 
      - main


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18] # Use a matrix strategy to use Node.js versions 16.x and 18.x

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      #- name: Use Node.js ${{ matrix.node-version }}
      - uses: 
        with:
          node-version: ${{ matrix.node-version }}

    